spring:
  application:
    name: backend
  jpa:
    generate-ddl: true
    open-in-view: false
#    hibernate:
#      ddl-auto: create
  datasource:
      url: jdbc:postgresql://localhost:5433/app_db
      username: postgres
      password: postgres
      hikari:
        schema: app_schema
        connection-timeout: 10000
